Updated fe and bb files to skip FE functions not implemented in FE

diff --git a/octal/rffe/fe-devicecontrol b/octal/rffe/fe-devicecontrol
--- a/octal/rffe/fe-devicecontrol
+++ b/octal/rffe/fe-devicecontrol
@@ -54,6 +54,17 @@ else
     done
 fi 
 
+HW_REVISION=$(fe-gethdrev 2> /dev/null)
+if [ $? -ne 0 ] ; then
+    echo "$0 - Error to get hardware revision "
+    exit 1
+fi
+
+if [ "$HW_REVISION" == "X" ]; then
+     echo 1
+     exit 0
+fi
+
 if [ ! -z $PA1 ]; then
     if [ $PA1 == "on" ]; then
         echo "enabled" > ${PA0_EN}
diff --git a/octal/rffe/fe-enable b/octal/rffe/fe-enable
--- a/octal/rffe/fe-enable
+++ b/octal/rffe/fe-enable
@@ -20,7 +20,15 @@ case $HW_REVISION in
 		echo 127 > ${SNIFF_ATT}
 		echo 0 > ${SNIFF_LNA_EN}
 		;;
-	C)
+	E )
+		
+		fe-setsniffercircuit --off 2> /dev/null
+		if [ $? -ne 0 ] ; then
+			echo "$0 - Error to set sniffer off "
+			exit 1
+		fi
+		;;
+	X )
 		echo "Benetel"
 oncpu 0 /usr/bin/cn_rfdriver << eof > /dev/null
 w
@@ -29,14 +37,6 @@ w
 q
 eof
 		exit 0
-		;;
-	E )
-		
-		fe-setsniffercircuit --off 2> /dev/null
-		if [ $? -ne 0 ] ; then
-			echo "$0 - Error to set sniffer off "
-			exit 1
-		fi
 		;;
 	* )
 		echo "Hardware Rev $HW_REVISION is not supported."
diff --git a/octal/rffe/fe-getreturnloss b/octal/rffe/fe-getreturnloss
--- a/octal/rffe/fe-getreturnloss
+++ b/octal/rffe/fe-getreturnloss
@@ -87,6 +87,17 @@ if [ -z $AVG_NUMBER ]; then
 	AVG_NUMBER=1;
 fi
 
+HW_REVISION=$(fe-gethdrev 2> /dev/null)
+if [ $? -ne 0 ] ; then
+    echo "$0 - Error to get hardware revision "
+    exit 1
+fi
+
+if [ "$HW_REVISION" == "X" ]; then
+     echo 1
+     exit 0
+fi
+
 somA=0
 somP=0
 somN=0
diff --git a/octal/rffe/fe-gettemperature b/octal/rffe/fe-gettemperature
--- a/octal/rffe/fe-gettemperature
+++ b/octal/rffe/fe-gettemperature
@@ -1,5 +1,8 @@
 #!/bin/sh
 
+HW_REVISION=""
+TEMP=
+
 usage()
 {
     echo "Usage: $0 <Temperature Sensor>"
@@ -14,42 +17,64 @@ if [ "$#" -ne 1 ]; then
     >&2 usage
     exit 1
 else
+    HW_REVISION=$(fe-gethdrev 2> /dev/null)
+    if [ $? -ne 0 ] ; then
+	echo "$0 - Error to get hardware revision "
+	exit 1
+    fi
+
     case $1 in
         -h | --help )
             usage
             exit
             ;;
         pa1 | PA1)
-			if [ -r /sys/devices/soc.0/1180000001200.i2c/i2c-1/1-004a/temp1_input ]; then
-				echo $(cat /sys/devices/soc.0/1180000001200.i2c/i2c-1/1-004a/temp1_input);
+        	if [ "$HW_REVISION" == "X" ]; then
+			echo 25000
+		else
+			if [ -r /sys/devices/soc.0/1180000001200.i2c/i2c-1/1-004a/temp1_input ]; then		
+				echo$(cat /sys/devices/soc.0/1180000001200.i2c/i2c-1/1-004a/temp1_input);
 			else
 				echo "$0 - ERROR PA1 temperature sensor is not detected"
 				exit 1
 			fi
+		fi
             ;;
         pa2 | PA2)
-			if [ -r /sys/devices/soc.0/1180000001000.i2c/i2c-0/0-004a/temp1_input ]; then
-				echo $(cat /sys/devices/soc.0/1180000001000.i2c/i2c-0/0-004a/temp1_input);
-            else
+        	if [ "$HW_REVISION" == "X" ]; then
+			echo 25000
+		else
+			if [ -r /sys/devices/soc.0/1180000001000.i2c/i2c-1/1-004a/temp1_input ]; then		
+				echo$(cat /sys/devices/soc.0/1180000001000.i2c/i2c-1/1-004a/temp1_input);
+			else
 				echo "$0 - ERROR PA2 temperature sensor is not detected"
 				exit 1
 			fi
-            ;;
+		fi
+           ;;
         fe | FE)
-			if [ -r /sys/devices/soc.0/1180000001200.i2c/i2c-1/1-0049/temp1_input ]; then
-				echo $(cat /sys/devices/soc.0/1180000001200.i2c/i2c-1/1-0049/temp1_input);
-            else
+        	if [ "$HW_REVISION" == "X" ]; then
+			echo 25000
+		else
+			if [ -r /sys/devices/soc.0/1180000001200.i2c/i2c-1/1-0049/temp1_input ]; then		
+				echo$(cat /sys/devices/soc.0/1180000001200.i2c/i2c-1/1-0049/temp1_input);
+			else
 				echo "$0 - ERROR Front-End temperature sensor is not detected"
 				exit 1
 			fi
+		fi
             ;;
         led | LED)
-			if [ -r /sys/devices/soc.0/1180000001200.i2c/i2c-1/1-004f/temp1_input ]; then
-				echo $(cat /sys/devices/soc.0/1180000001200.i2c/i2c-1/1-004f/temp1_input);
-            else
-				echo "$0 - ERROR LED Board temperature sensor is not detected"
+        	if [ "$HW_REVISION" == "X" ]; then
+			echo 25000
+		else
+			if [ -r /sys/devices/soc.0/1180000001200.i2c/i2c-1/1-0049/temp1_input ]; then		
+				echo$(cat /sys/devices/soc.0/1180000001200.i2c/i2c-1/1-0049/temp1_input);
+			else
+				echo "$0 - ERROR LED board temperature sensor is not detected"
 				exit 1
 			fi
+		fi
             ;;
         * )
             usage
diff --git a/octal/rffe/fe-gettxpower b/octal/rffe/fe-gettxpower
--- a/octal/rffe/fe-gettxpower
+++ b/octal/rffe/fe-gettxpower
@@ -59,6 +59,16 @@ else
     done
 fi
 
+HW_REVISION=$(fe-gethdrev 2> /dev/null)
+if [ $? -ne 0 ] ; then
+    echo "$0 - Error to get hardware revision "
+    exit 1
+fi
+
+if [ "$HW_REVISION" == "X" ]; then
+     exit 0
+fi
+
 if [ ${TX_CHANNEL} -eq 1 ]; then
 	if [ -r /sys/devices/soc.0/1180000001200.i2c/i2c-1/1-0040/curr1_input ]; then
 		X="$(cat /sys/devices/soc.0/1180000001200.i2c/i2c-1/1-0028/iio:device1/in_voltage0_raw)"
diff --git a/octal/rffe/fe-manager b/octal/rffe/fe-manager
--- a/octal/rffe/fe-manager
+++ b/octal/rffe/fe-manager
@@ -1,6 +1,6 @@
 #!/bin/sh
 
-VERSION=1.3
+VERSION=2.0
 
 HW_REVISION_SUPPORTED="A D E"
 
@@ -39,9 +39,9 @@ VSWR_TX_OK=0
 VSWR_TX_WARNING=1
 VSWR_TX_OPEN=2
 ALERT_CODE_OK=0
-ALERT_CODE_HIGHT_TEMP=1
+ALERT_CODE_HIGH_TEMP=1
 ALERT_CODE_LOW_TEMP=2
-ALERT_CODE_HIGHT_CURRENT=3
+ALERT_CODE_HIGH_CURRENT=3
 CELL_STATE_UP=0
 CELL_STATE_IDLE=1
 CELL_STATE_UNKNOWN=2
@@ -63,6 +63,7 @@ flagAlerts=$ALERT_CODE_OK
 stateCell=$CELL_STATE_IDLE
 
 ledboardColor=$LED_COLOR_OFF
+fe-setled off
 
 counterReadjustTxPower=0
 counterCellStateCheck=0
@@ -189,7 +190,7 @@ DESCRIPTION
 	exit 1
 }
 
-log $LOG_LEVEL_NOTICE "fe-manger V$VERSION start"
+log $LOG_LEVEL_NOTICE "fe-manager V$VERSION start"
 
 while [ $# -gt 0 ] ; do
 	case "$1" in
@@ -241,7 +242,6 @@ while [ $# -gt 0 ] ; do
 	esac
 	shift
 done
-
 
 
 TX_FREQ_ARG=${TX_FREQ}
@@ -335,12 +335,11 @@ loop()
 			log $LOG_LEVEL_EMERGENCY "could not get Front-End temperature"
 			exit 1
 		fi
-		#FIXME commenting out LED for now
-		#tempLed=$(fe-gettemperature  led)
-		#if [ $? -ne 0 ] ; then
-		#	log $LOG_LEVEL_EMERGENCY "could not get LED Board temperature, NO EXIT"
-		#	#exit 1
-		#fi
+		tempLed=$(fe-gettemperature  led)
+		if [ $? -ne 0 ] ; then
+			log $LOG_LEVEL_EMERGENCY "could not get LED Board temperature, NO EXIT"
+			#exit 1
+		fi
 
 		########## Get Current ##############
 		currentPa1=$(fe-getcurrent  pa1)
@@ -353,7 +352,6 @@ loop()
 			log $LOG_LEVEL_EMERGENCY "could not get PA2 current"
 			exit 1
 		fi
-
 
 		########## Get TX ADC Value ##############
 		adcValueTx1=$(fe-gettxpower -t 1 -f ADC)
@@ -386,13 +384,13 @@ loop()
 
 		#********		PA 1		********#
 		if [ $tempPa1 -gt $tempPa1Max ]; then
-			flagAlertPa1=$ALERT_CODE_HIGHT_TEMP
+			flagAlertPa1=$ALERT_CODE_HIGH_TEMP
 			log $LOG_LEVEL_ALERT "PA 1 High Temp : $tempPa1 mC"
 		elif [ $tempPa1 -lt $tempPa1Min ]; then
 			flagAlertPa1=$ALERT_CODE_LOW_TEMP
 			log $LOG_LEVEL_ALERT "PA 1 Low Temp : $tempPa1 mC"
 		elif [ $currentPa1 -gt $currentPa1Max ]; then
-			flagAlertPa1=$ALERT_CODE_HIGHT_CURRENT
+			flagAlertPa1=$ALERT_CODE_HIGH_CURRENT
 			log $LOG_LEVEL_ALERT "PA 1 High Current : $currentPa1 mA"
 		else
 			flagAlertPa1=$ALERT_CODE_OK
@@ -400,51 +398,51 @@ loop()
 
 		#********		PA 2		********#
 		if [ $tempPa2 -gt $tempPa2Max ]; then
-			flagAlertPa2=$ALERT_CODE_HIGHT_TEMP
+			flagAlertPa2=$ALERT_CODE_HIGH_TEMP
 			log $LOG_LEVEL_ALERT "PA 2 High Temp : $tempPa2 mC "
 		elif [ $tempPa2 -lt $tempPa2Min ]; then
 			flagAlertPa2=$ALERT_CODE_LOW_TEMP
 			log $LOG_LEVEL_ALERT "PA 2 Low Temp : $tempPa2 mC"
 		elif [ $currentPa2 -gt $currentPa2Max ]; then
-			flagAlertPa2=$ALERT_CODE_HIGHT_CURRENT
+			flagAlertPa2=$ALERT_CODE_HIGH_CURRENT
 			log $LOG_LEVEL_ALERT "PA 2 High Current : $currentPa2 mA"
 		else
 			flagAlertPa2=$ALERT_CODE_OK
 		fi
+# FIXME These variable are not even being set, so we need to set them and then enable the comparison again
 		#********		TX 1		********#
-		if [ $adcValueTx1 -gt $txPowerActiveLevelAdcValueMin ]; then
-			flagStateTx1=$STATE_TX_ACTIVE
-		else
-			flagStateTx1=$STATE_TX_IDLE
-		fi
+#		if [ $adcValueTx1 -gt $txPowerActiveLevelAdcValueMin ]; then
+#			flagStateTx1=$STATE_TX_ACTIVE
+#		else
+#			flagStateTx1=$STATE_TX_IDLE
+#		fi
 
-		if [ $vswrmValueTx1 -gt $vswrOpenLevelMin ]; then
-			flagVswrTx1=$VSWR_TX_OPEN
-		elif [ $vswrmValueTx1 -gt $vswrWarningLevelMin ]; then
-			flagVswrTx1=$VSWR_TX_WARNING
-		else
-			flagVswrTx1=$VSWR_TX_OK
-		fi
-
+#		if [ $vswrmValueTx1 -gt $vswrOpenLevelMin ]; then
+#			flagVswrTx1=$VSWR_TX_OPEN
+#		elif [ $vswrmValueTx1 -gt $vswrWarningLevelMin ]; then
+#			flagVswrTx1=$VSWR_TX_WARNING
+#		else
+#			flagVswrTx1=$VSWR_TX_OK
+#		fi
 
 		#********		TX 2		********#
-		if [ $adcValueTx2 -gt $txPowerActiveLevelAdcValueMin ]; then
-			flagStateTx2=$STATE_TX_ACTIVE
-		else
-			flagStateTx2=$STATE_TX_IDLE
-		fi
+#		if [ $adcValueTx2 -gt $txPowerActiveLevelAdcValueMin ]; then
+#			flagStateTx2=$STATE_TX_ACTIVE
+#		else
+#			flagStateTx2=$STATE_TX_IDLE
+#		fi
 
-		if [ $vswrmValueTx2 -gt $vswrOpenLevelMin ]; then
-			flagVswrTx2=$VSWR_TX_OPEN
-		elif [ $vswrmValueTx2 -gt $vswrWarningLevelMin ]; then
-			flagVswrTx2=$VSWR_TX_WARNING
-		else
-			flagVswrTx2=$VSWR_TX_OK
-		fi
+#		if [ $vswrmValueTx2 -gt $vswrOpenLevelMin ]; then
+#			flagVswrTx2=$VSWR_TX_OPEN
+#		elif [ $vswrmValueTx2 -gt $vswrWarningLevelMin ]; then
+#			flagVswrTx2=$VSWR_TX_WARNING
+#		else
+#			flagVswrTx2=$VSWR_TX_OK
+#		fi
 
 		#********		FE		********#
 		if [ $tempFe -gt $tempFeMax ]; then
-			flagAlertFe=$ALERT_CODE_HIGHT_TEMP
+			flagAlertFe=$ALERT_CODE_HIGH_TEMP
 			log $LOG_LEVEL_ALERT "FE High Temp : $tempFe mC"
 		elif [ $tempFe -lt $tempFeMin ]; then
 			flagAlertFe=$ALERT_CODE_LOW_TEMP
@@ -453,21 +451,20 @@ loop()
 			flagAlertFe=$ALERT_CODE_OK
 		fi
 
-		#FIXME commenting out LED for now
 		#********		LED		********#
-		#if [ $tempLed -gt $tempLedMax ]; then
-		#	flagAlertLed=$ALERT_CODE_HIGHT_TEMP
-		#	log $LOG_LEVEL_ALERT "LED High Temp : $tempLed mC"
-		#elif [ $tempLed -lt $tempLedMin ]; then
-		#	flagAlertLed=$ALERT_CODE_LOW_TEMP
-		#	log $LOG_LEVEL_ALERT "LED Low Temp : $tempLed mC"
-		#else
-		#	flagAlertLed=$ALERT_CODE_OK
-		#fi
+		if [ $tempLed -gt $tempLedMax ]; then
+			flagAlertLed=$ALERT_CODE_HIGH_TEMP
+			log $LOG_LEVEL_ALERT "LED High Temp : $tempLed mC"
+		elif [ $tempLed -lt $tempLedMin ]; then
+			flagAlertLed=$ALERT_CODE_LOW_TEMP
+			log $LOG_LEVEL_ALERT "LED Low Temp : $tempLed mC"
+		else
+			flagAlertLed=$ALERT_CODE_OK
+		fi
 
 		#********	ALERT Flag	********#
 		if [ $flagAlertPa1 -ne 0 -o $flagAlertPa2 -ne 0 -o $flagAlertFe -ne 0 -o $flagAlertLed -ne 0 ] ; then
-			flagAlerts=$ALERT_CODE_HIGHT_TEMP
+			flagAlerts=$ALERT_CODE_HIGH_TEMP
 		else
 			flagAlerts=$ALERT_CODE_OK
 		fi
@@ -480,30 +477,28 @@ loop()
 		#********	  Cell State	********#
 		if [ $stateCell -ne $CELL_STATE_UP ] ; then
 			log $LOG_LEVEL_WARNING "Cell is Down! Turn on Red LED!"
-		#FIXME commenting out LED for now
-		#	ledboardColor=$LED_COLOR_RED
-		#else
-		#	ledboardColor=$LED_COLOR_GREEN
+			ledboardColor=$LED_COLOR_RED
+		else
+			ledboardColor=$LED_COLOR_GREEN
 		fi
 		#********		Alert		********#
 		if [ $flagAlerts -ne $ALERT_CODE_OK ] ; then
 			log $LOG_LEVEL_WARNING "Alert! Turn on Orange LED!"
-		#FIXME commenting out LED for now
-		#	ledboardColor=$LED_COLOR_ORANGE
+			ledboardColor=$LED_COLOR_ORANGE
 
-			if [ $flagAlertPa1 -eq $ALERT_CODE_HIGHT_CURRENT ] ; then
+			if [ $flagAlertPa1 -eq $ALERT_CODE_HIGH_CURRENT ] ; then
 				fe-devicecontrol -PA1 off
 				if [ $? -ne 0 ] ; then
-					log $LOG_LEVEL_CRITICAL "Could not turn off PA1 : fe-devicecontrol faillure"
+					log $LOG_LEVEL_CRITICAL "Could not turn off PA1 : fe-devicecontrol failure"
 					exit 1
 				fi
 				log $LOG_LEVEL_ALERT "PA1 Turn off"
 			fi
 
-			if [ $flagAlertPa2 -eq $ALERT_CODE_HIGHT_CURRENT ] ; then
+			if [ $flagAlertPa2 -eq $ALERT_CODE_HIGH_CURRENT ] ; then
 				fe-devicecontrol -PA2 off
 				if [ $? -ne 0 ] ; then
-					log $LOG_LEVEL_CRITICAL "Could not turn off PA2 : fe-devicecontrol faillure"
+					log $LOG_LEVEL_CRITICAL "Could not turn off PA2 : fe-devicecontrol failure"
 					exit 1
 				fi
 				log $LOG_LEVEL_ALERT "PA2 Turn off"
@@ -516,8 +511,7 @@ loop()
 				if [ $flagVswrTx1 -eq $VSWR_TX_WARNING ] ; then
 					log $LOG_LEVEL_WARNING "TX 1 VSWR High : $flagVswrTx1"
 				elif [ $flagVswrTx1 -eq $VSWR_TX_OPEN ] ; then
-					#FIXME commenting out LED for now
-					#ledboardColor=$LED_COLOR_ORANGE
+					ledboardColor=$LED_COLOR_ORANGE
 					log $LOG_LEVEL_ALERT "TX 1 lost antenna, VSWR : $flagVswrTx1"
 				fi
 			fi
@@ -527,34 +521,32 @@ loop()
 				if [ $flagVswrTx2 -eq $VSWR_TX_WARNING ] ; then
 					log $LOG_LEVEL_WARNING "TX 2 VSWR High : $flagVswrTx1"
 				elif [ $flagVswrTx2 -eq $VSWR_TX_OPEN ] ; then
-					#FIXME commenting out LED for now
-					#ledboardColor=$LED_COLOR_ORANGE
+					ledboardColor=$LED_COLOR_ORANGE
 					log $LOG_LEVEL_ALERT "TX 2 lost antenna, VSWR : $flagVswrTx1"
 				fi
 			fi
 		fi
 
-		#FIXME commenting out LED for now
 		#********	Set LED Color	********#
-		#if [ ${ledboardColor} -eq ${LED_COLOR_ORANGE} ]; then
-		#	fe-setled orange on
-		#	if [ $? -ne 0 ] ; then
-		#		log $LOG_LEVEL_CRITICAL "fe-setled faillure to set orange color"
-		#		exit 1
-		#	fi
-		#elif [ ${ledboardColor} -eq ${LED_COLOR_RED} ]; then
-		#	fe-setled red on
-		#	if [ $? -ne 0 ] ; then
-		#		log $LOG_LEVEL_CRITICAL "fe-setled faillure to set red color"
-		#		exit 1
-		#	fi
-		#elif [ ${ledboardColor} -eq ${LED_COLOR_GREEN} ]; then
-		#	fe-setled green on
-		#	if [ $? -ne 0 ] ; then
-		#		log $LOG_LEVEL_CRITICAL "fe-setled faillure to set green color"
-		#		exit 1
-		#	fi
-		#fi
+		if [ ${ledboardColor} -eq ${LED_COLOR_ORANGE} ]; then
+			fe-setled orange on
+			if [ $? -ne 0 ] ; then
+				log $LOG_LEVEL_CRITICAL "fe-setled failure to set orange color"
+				exit 1
+			fi
+		elif [ ${ledboardColor} -eq ${LED_COLOR_RED} ]; then
+			fe-setled red on
+			if [ $? -ne 0 ] ; then
+				log $LOG_LEVEL_CRITICAL "fe-setled failure to set red color"
+				exit 1
+			fi
+		elif [ ${ledboardColor} -eq ${LED_COLOR_GREEN} ]; then
+			fe-setled green on
+			if [ $? -ne 0 ] ; then
+				log $LOG_LEVEL_CRITICAL "fe-setled failure to set green color"
+				exit 1
+			fi
+		fi
 
 		#********	  Readjust TX	********#
 		if [ $counterReadjustTxPower -ge $periodReadjustTx ]; then
@@ -565,7 +557,7 @@ loop()
 				fe-readjusttxatt --txfreq ${TX_FREQ} --calfiles $CALFILES_DIR
 			fi
 			if [ $? -ne 0 ] ; then
-				log $LOG_LEVEL_CRITICAL "fe-readjusttxatt faillure"
+				log $LOG_LEVEL_CRITICAL "fe-readjusttxatt failure"
 				exit 1
 			fi
 			log $LOG_LEVEL_INFORMATIONAL "Readjust TX Att"
diff --git a/octal/rffe/fe-readjusttxatt b/octal/rffe/fe-readjusttxatt
--- a/octal/rffe/fe-readjusttxatt
+++ b/octal/rffe/fe-readjusttxatt
@@ -107,7 +107,16 @@ while [ $# -gt 0 ] ; do
     shift
 done
 
-TX_FREQ_ARG=${TX_FREQ}
+HW_REVISION=$(fe-gethdrev 2> /dev/null)
+if [ $? -ne 0 ] ; then
+    echo "$0 - Error to get hardware revision "
+    exit 1
+fi
+
+if [ "$HW_REVISION" == "X" ]; then
+     exit 0
+fi
+
 ####################  Source system.conf  #######################
 if [ ! -z $SYSCFG_DIR ] ; then
     if [ -f "$SYSCFG_DIR/$SYSCFG_FILE_NAME" ] ; then
@@ -157,9 +166,6 @@ fi
 
 TX_FREQ=$(echo ${TX_FREQ} | cut -d "." -f 1)
 
-if [ ! -z ${TX_FREQ_ARG} ] ; then
-	TX_FREQ=${TX_FREQ_ARG}
-fi
 #######################  Check BandWidth  #######################
 if [ -z $TX_BW ] ; then
     TX_BW=${BW}
diff --git a/octal/rffe/fe-setled b/octal/rffe/fe-setled
--- a/octal/rffe/fe-setled
+++ b/octal/rffe/fe-setled
@@ -1,5 +1,6 @@
 #!/bin/sh
 
+HW_REVISION=""
 
 usage()
 {
@@ -13,32 +14,58 @@ usage()
 
 turnOffAllLeds()
 {
-    for i in /sys/devices/soc.0/0.leds/leds/* ;do
-        echo 0 > $i/brightness
-        if [ $? -ne 0 ] ; then
-            echo "$0 - Error Set LED OFF : $i/brightness"
-            exit 1
-        fi
-    done
+    if [ "$HW_REVISION" == "X" ]; then
+        # init i2c expanders to drive LEDs
+        i2cset -y 0 0x3E 0x0A 0xFF > /dev/null
+        i2cset -y 0 0x3E 0x0B 0xFF > /dev/null
+        i2cset -y 0 0x3E 0x0C 0xFF > /dev/null
+        i2cset -y 0 0x3E 0x0D 0xFF > /dev/null
+        i2cset -y 0 0x3F 0x0A 0xFF > /dev/null
+        i2cset -y 0 0x3F 0x0B 0xFF > /dev/null
+        i2cset -y 0 0x3F 0x0C 0xFF > /dev/null
+        i2cset -y 0 0x3F 0x0D 0xFF > /dev/null
+    
+        # set LEDs off
+        i2cset -y 0 0x3E 0x10 0x00 > /dev/null
+        i2cset -y 0 0x3E 0x11 0x00 > /dev/null
+        i2cset -y 0 0x3F 0x10 0x00 > /dev/null
+        i2cset -y 0 0x3F 0x11 0x00 > /dev/null
+    else
+        for i in /sys/devices/soc.0/0.leds/leds/* ;do
+            echo 0 > $i/brightness
+            if [ $? -ne 0 ] ; then
+                echo "$0 - Error Set LED OFF : $i/brightness"
+                exit 1
+            fi
+        done
+    fi
 }
 
 redLed()
 {
     if [ "$1" == "on" ]; then
-        for i in /sys/devices/soc.0/0.leds/leds/red* ;do
-            echo 255 > $i/brightness
-            if [ $? -ne 0 ] ; then
-                echo "$0 - Error Set RED LED ON : $i/brightness"
-                exit 1
-            fi
-        done
-        for i in /sys/devices/soc.0/0.leds/leds/green* ;do
-            echo 0 > $i/brightness
-            if [ $? -ne 0 ] ; then
-                echo "$0 - Error Set RED LED ON : $i/brightness"
-                exit 1
-            fi
-        done
+        if [ "$HW_REVISION" == "X" ]; then
+            # set red LEDs on
+            i2cset -y 0 0x3E 0x10 0x55 > /dev/null
+            i2cset -y 0 0x3E 0x11 0x55 > /dev/null
+            i2cset -y 0 0x3F 0x10 0x55 > /dev/null
+            i2cset -y 0 0x3F 0x11 0x55 > /dev/null
+        else
+            for i in /sys/devices/soc.0/0.leds/leds/red* ;do
+                echo 255 > $i/brightness
+                if [ $? -ne 0 ] ; then
+                    echo "$0 - Error Set RED LED ON : $i/brightness"
+                    exit 1
+                fi
+            done
+            for i in /sys/devices/soc.0/0.leds/leds/green* ;do
+                echo 0 > $i/brightness
+                if [ $? -ne 0 ] ; then
+                    echo "$0 - Error Set RED LED ON : $i/brightness"
+                    exit 1
+                fi
+            done
+        fi
     elif [ "$1" == "off" ]; then
         turnOffAllLeds
     else
@@ -51,20 +78,28 @@ redLed()
 greenLed()
 {
     if [ "$1" == "on" ]; then
-        for i in /sys/devices/soc.0/0.leds/leds/red* ;do
-            echo 0 > $i/brightness
-            if [ $? -ne 0 ] ; then
-                echo "$0 - Error Set LED GREEN ON : $i/brightness"
-                exit 1
-            fi
-        done
-        for i in /sys/devices/soc.0/0.leds/leds/green* ;do
-            echo 255 > $i/brightness
-            if [ $? -ne 0 ] ; then
-                echo "$0 - Error Set LED GREEN ON : $i/brightness"
-                exit 1
-            fi
-        done
+        if [ "$HW_REVISION" == "X" ]; then
+            # set red LEDs on
+            i2cset -y 0 0x3E 0x10 0xAA > /dev/null
+            i2cset -y 0 0x3E 0x11 0xAA > /dev/null
+            i2cset -y 0 0x3F 0x10 0xAA > /dev/null
+            i2cset -y 0 0x3F 0x11 0xAA > /dev/null
+        else
+            for i in /sys/devices/soc.0/0.leds/leds/red* ;do
+                echo 0 > $i/brightness
+                if [ $? -ne 0 ] ; then
+                    echo "$0 - Error Set LED GREEN ON : $i/brightness"
+                    exit 1
+                fi
+            done
+            for i in /sys/devices/soc.0/0.leds/leds/green* ;do
+                echo 255 > $i/brightness
+                if [ $? -ne 0 ] ; then
+                    echo "$0 - Error Set LED GREEN ON : $i/brightness"
+                    exit 1
+                fi
+            done
+        fi
     elif [ "$1" == "off" ]; then
         turnOffAllLeds
     else
@@ -76,20 +111,28 @@ greenLed()
 orangeLed()
 {
     if [ "$1" == "on" ]; then
-        for i in /sys/devices/soc.0/0.leds/leds/red* ;do
-            echo 255 > $i/brightness
-            if [ $? -ne 0 ] ; then
-                echo "$0 - Error Set LED ORANGE ON : $i/brightness"
-                exit 1
-            fi
-        done
-        for i in /sys/devices/soc.0/0.leds/leds/green* ;do
-            echo 255 > $i/brightness
-            if [ $? -ne 0 ] ; then
-                echo "$0 - Error Set LED ORANGE ON : $i/brightness"
-                exit 1
-            fi
-        done
+        if [ "$HW_REVISION" == "X" ]; then
+            # set red LEDs on
+            i2cset -y 0 0x3E 0x10 0xFF > /dev/null
+            i2cset -y 0 0x3E 0x11 0xFF > /dev/null
+            i2cset -y 0 0x3F 0x10 0xFF > /dev/null
+            i2cset -y 0 0x3F 0x11 0xFF > /dev/null
+        else
+            for i in /sys/devices/soc.0/0.leds/leds/red* ;do
+                echo 255 > $i/brightness
+                if [ $? -ne 0 ] ; then
+                    echo "$0 - Error Set LED ORANGE ON : $i/brightness"
+                    exit 1
+                fi
+            done
+            for i in /sys/devices/soc.0/0.leds/leds/green* ;do
+                echo 255 > $i/brightness
+                if [ $? -ne 0 ] ; then
+                    echo "$0 - Error Set LED ORANGE ON : $i/brightness"
+                    exit 1
+                fi
+            done
+        fi
     elif [ "$1" == "off" ]; then
         turnOffAllLeds
     else
@@ -105,6 +148,12 @@ if [ "$1" == "" ]; then
     >&2 usage
     exit 1
 else
+    HW_REVISION=$(fe-gethdrev 2> /dev/null)
+    if [ $? -ne 0 ] ; then
+	echo "$0 - Error to get hardware revision "
+	exit 1
+    fi
+
     case $1 in
         -h | --help )
             usage
diff --git a/octal/rffe/pltd-enablefe b/octal/rffe/pltd-enablefe
--- a/octal/rffe/pltd-enablefe
+++ b/octal/rffe/pltd-enablefe
@@ -130,6 +130,9 @@ fi
 
 TX_FREQ=$(echo ${TX_FREQ} | cut -d "." -f 1)
 
+#################  Get Band  #####################
+TX_BAND=$(bb-gettxband ${TX_FREQ} 2> /dev/null)
+
 #######################  Check BandWidth  #######################
 if [ -z $TX_BW ] ; then
     TX_BW=${BW}
@@ -153,7 +156,6 @@ if [ $? -ne 0 ] ; then
     exit 1
 fi
 
-
 bb-settxatt 1 ${CAL_BB_ATT_TX1} 2> /dev/null
 if [ $? -ne 0 ] ; then
     echo "$0 - Error Set BB Attenuation TX1"
@@ -166,7 +168,6 @@ if [ $? -ne 0 ] ; then
     exit 1
 fi
 
-
 ##########################  Enable FE  ##########################
 fe-enable 2> /dev/null
 if [ $? -ne 0 ] ; then
@@ -174,57 +175,59 @@ if [ $? -ne 0 ] ; then
     exit 1
 fi
 
-#################  Set FE FB Attenuation  #######################
-CAL_FE_FB_ATT_TX1=$(cal-getfefbatt ${TX_BW} 1 ${TX_FREQ} ${TX_POWER} $CALFILES_DIR 2> /dev/null)
-if [ $? -ne 0 ] ; then
-    echo "$0 - Error Get FE FB Attenuation TX1: $CAL_BB_ATT_TX1"
-    exit 1
+if [ ${TX_BAND} -eq 3 ] ; then
+
+    #################  Set FE FB Attenuation  #######################
+    CAL_FE_FB_ATT_TX1=$(cal-getfefbatt ${TX_BW} 1 ${TX_FREQ} ${TX_POWER} $CALFILES_DIR 2> /dev/null)
+    if [ $? -ne 0 ] ; then
+        echo "$0 - Error Get FE FB Attenuation TX1: $CAL_BB_ATT_TX1"
+        exit 1
+    fi
+
+    CAL_FE_FB_ATT_TX2=$(cal-getfefbatt ${TX_BW} 2 ${TX_FREQ} ${TX_POWER} $CALFILES_DIR 2> /dev/null)
+    if [ $? -ne 0 ] ; then
+        echo "$0 - Error Get FE FB Attenuation TX2: $CAL_BB_ATT_TX1"
+        exit 1
+    fi
+
+    fe-setfbatt 1 ${CAL_FE_FB_ATT_TX1} 2> /dev/null
+    if [ $? -ne 0 ] ; then
+        echo "$0 - Error Set FE FB Attenuation TX1"
+        exit 1
+    fi
+
+    fe-setfbatt 2 ${CAL_FE_FB_ATT_TX2} 2> /dev/null
+    if [ $? -ne 0 ] ; then
+        echo "$0 - Error Set FE FB Attenuation TX2"
+        exit 1
+    fi
+
+    #################  Set FE TX Attenuation  #######################
+    CAL_FE_TX_ATT_TX1=$(cal-getfetxatt -b ${TX_BW} -a 1 -f ${TX_FREQ} -p ${TX_POWER} -c $CALFILES_DIR -t 2> /dev/null)
+    if [ $? -ne 0 ] ; then
+        echo "$0 - Error Set FE TX Attenuation TX1: $CAL_BB_ATT_TX1"
+        exit 1
+    fi
+
+    CAL_FE_TX_ATT_TX2=$(cal-getfetxatt -b ${TX_BW} -a 2 -f ${TX_FREQ} -p ${TX_POWER} -c $CALFILES_DIR -t 2> /dev/null)
+    if [ $? -ne 0 ] ; then
+        echo "$0 - Error Set FE TX Attenuation TX2: $CAL_BB_ATT_TX1"
+        exit 1
+    fi
+
+    fe-settxatt 1 ${CAL_FE_TX_ATT_TX1} 2> /dev/null
+    if [ $? -ne 0 ] ; then
+        echo "$0 - Error Set FE TX Attenuation TX1"
+        exit 1
+    fi
+
+    fe-settxatt 2 ${CAL_FE_TX_ATT_TX2} 2> /dev/null
+    if [ $? -ne 0 ] ; then
+        echo "$0 - Error Set FE TX Attenuation TX2"
+        exit 1
+    fi
+
+    ####################  Reset RFPAL  ##############################
+    fe-resetrfpal
+
 fi
-
-CAL_FE_FB_ATT_TX2=$(cal-getfefbatt ${TX_BW} 2 ${TX_FREQ} ${TX_POWER} $CALFILES_DIR 2> /dev/null)
-if [ $? -ne 0 ] ; then
-    echo "$0 - Error Get FE FB Attenuation TX2: $CAL_BB_ATT_TX1"
-    exit 1
-fi
-
-
-fe-setfbatt 1 ${CAL_FE_FB_ATT_TX1} 2> /dev/null
-if [ $? -ne 0 ] ; then
-    echo "$0 - Error Set FE FB Attenuation TX1"
-    exit 1
-fi
-
-fe-setfbatt 2 ${CAL_FE_FB_ATT_TX2} 2> /dev/null
-if [ $? -ne 0 ] ; then
-    echo "$0 - Error Set FE FB Attenuation TX2"
-    exit 1
-fi
-
-#################  Set FE TX Attenuation  #######################
-CAL_FE_TX_ATT_TX1=$(cal-getfetxatt -b ${TX_BW} -a 1 -f ${TX_FREQ} -p ${TX_POWER} -c $CALFILES_DIR -t 2> /dev/null)
-if [ $? -ne 0 ] ; then
-    echo "$0 - Error Set FE TX Attenuation TX1: $CAL_BB_ATT_TX1"
-    exit 1
-fi
-
-CAL_FE_TX_ATT_TX2=$(cal-getfetxatt -b ${TX_BW} -a 2 -f ${TX_FREQ} -p ${TX_POWER} -c $CALFILES_DIR -t 2> /dev/null)
-if [ $? -ne 0 ] ; then
-    echo "$0 - Error Set FE TX Attenuation TX2: $CAL_BB_ATT_TX1"
-    exit 1
-fi
-
-
-fe-settxatt 1 ${CAL_FE_TX_ATT_TX1} 2> /dev/null
-if [ $? -ne 0 ] ; then
-    echo "$0 - Error Set FE TX Attenuation TX1"
-    exit 1
-fi
-
-fe-settxatt 2 ${CAL_FE_TX_ATT_TX2} 2> /dev/null
-if [ $? -ne 0 ] ; then
-    echo "$0 - Error Set FE TX Attenuation TX2"
-    exit 1
-fi
-
-####################  Reset RFPAL  ##############################
-fe-resetrfpal
