Add NVRAM size limit to nano-emulator and add test to recover from NVRAM hog attack.
Change-Id: I58265ddf26f2e93b9057fe6b95fb3c1b98e82e99

Add NVRAM-hogging DOS attack.

Change-Id: Ia178e42539a771747ab8a96560eb2d374ed07904

BUG=none
TEST=passes included test

Review URL: http://codereview.chromium.org/4183005

diff --git a/utility/chromeos_tpm_recovery b/utility/chromeos_tpm_recovery
--- a/utility/chromeos_tpm_recovery
+++ b/utility/chromeos_tpm_recovery
@@ -72,9 +72,10 @@ tpm_clear_and_reenable () {
   tpm_unowned=1
 }
 
+# We want the TPM owned with the well-known password.
+
 ensure_tpm_is_owned () {
-  if [ $tpm_owned_with_well_known_password = 0 -a \
-       $tpm_unowned = 0 ]; then
+  if [ $tpm_owned_with_well_known_password = 0 ]; then
     tpm_clear_and_reenable
     ensure_tcsd_is_running
     $tpm_takeownership -y -z || log "takeownership failed with status $?"
@@ -116,16 +117,20 @@ make_room () {
 /# NV Index / { print $4 } #unexpected space
 EOF
 
+  local index
+
+  log "trying to make room by freeing one space"
   ensure_tcsd_is_running
   ensure_tpm_is_owned
   unexpected_spaces=$($nvtool --list | $awk -f $AWK_PROGRAM)
 
   status=1
 
-  if ("$unexpected_spaces" != ""); then
+  if [ "$unexpected_spaces" != "" ]; then
     log_tryfix "unexpected spaces: $unexpected_spaces"
     for index in $unexpected_spaces; do
-      if remove_space $index; then
+      log "trying to remove space $index"
+      if remove_space $(printf "0x%x" $(( $index )) ); then
         status=0
         break;
       fi
@@ -148,10 +153,13 @@ define_space () {
 
   ensure_tpm_is_unowned
   while true; do
+    log "checking for NVRAM room for space with size $size"
     if $tpmc definespace $test_space $size $perm_ppwrite; then
+      log "there is enough room"
       enough_room=1
       break
     else
+      log "definespace $test_space $size failed with status $?"
       if ! make_room; then
         enough_room=0
         break
@@ -228,7 +236,7 @@ fix_space () {
 if [ $# = 1 ]; then
   RECOVERY_LOG="$1"
   /usr/bin/logger "$0 started, output in $RECOVERY_LOG"
-  log "starting"
+  log "starting $0"
 else
   /usr/bin/logger "$0 usage error"
   echo "usage: $0 <log file>"
diff --git a/utility/chromeos_tpm_recovery_test b/utility/chromeos_tpm_recovery_test
--- a/utility/chromeos_tpm_recovery_test
+++ b/utility/chromeos_tpm_recovery_test
@@ -23,6 +23,8 @@ echo > .recovery
 echo 3 > BINF.0
 echo 0 > CRSW
 
+space_overhead=200
+
 # build tpmc
 cat > tpmc <<"EOF"
 #!/bin/sh -u
@@ -32,9 +34,18 @@ definespace () {
   index=$2
   size=$3
   permissions=$4
+  space_overhead=200
 
   if [ -e space.$index.data -a -e tpm-owned ]; then
     echo "cannot redefine space without auth"
+  fi
+
+  totalsize=$(( $size + $space_overhead ))
+  free=$(cat nvram.freespace)
+
+  if [ $totalsize -gt $free ]; then
+    echo "tpmc: definespace: need $totalsize, available $free"
+    return 17  # NO_SPACE
   fi
 
   if [ $index != 0xf004 ]; then
@@ -43,6 +54,7 @@ definespace () {
     for i in $(seq 1 $(($size))); do
       echo -n "ff " >> space.$index.data
     done
+    echo $(( $free - $totalsize )) > nvram.freespace
   fi
   return 0
 }
@@ -130,9 +142,11 @@ EOF
 cat > tpm-nvtool <<"EOF"
 #!/bin/sh -u
 
+space_overhead=200
+
 print_space () {
   index=$1
-  echo "# NV Index $index"
+  printf "# NV Index 0x%08x" $(( $index ))
   echo " uninteresting random garbage"
   echo " further random garbage"
   echo ""
@@ -149,7 +163,10 @@ if [ "$1" = "--release" ]; then
     echo "tpm is unowned"
     exit 1
   fi
+  size=$(cat space.$index.size)
+  free=$(cat nvram.freespace)
   rm space.$index.*
+  echo $(( $size + $space_overhead + $free )) > nvram.freespace
 elif [ "$1" = "--list" ]; then
   for s in space.*.data; do
     print_space $(echo $s | sed -e "s/[^.]*\.//" -e "s/\..*//")
@@ -180,34 +197,54 @@ chmod 755 tpmc tpm-nvtool tpm_takeownership tcsd
 echo "starting TPM recovery test" > log
 
 # normal run
+echo "TEST: normal run" > log
+
+echo 1500 > nvram.freespace
 
 ./tpmc definespace 0x1007 0xa 0x8001
 ./tpmc definespace 0x1008 0xd 0x1
 ./tpmc write 0x1008 01 4c 57 52 47
 touch tpm-owned
 
-echo "TEST: normal run" > log
 $ctr log
 
-# attempt to hijack kernel space
+# Kernel space with wrong ID
+echo "TEST: bad kernel space ID" >> log
 
 rm space.*
+echo 1500 > nvram.freespace
 
 ./tpmc definespace 0x1007 0xa 0x8001
 ./tpmc definespace 0x1008 0xd 0x1
 touch tpm-owned
 
-echo "TEST: bad kernel space ID" >> log
 $ctr log
 
-# attempt to hijack kernel space
+# Kernel space with wrong size
+echo "TEST: bad kernel space size" >> log
 
 rm space.*
+echo 1500 > nvram.freespace
 
 ./tpmc definespace 0x1007 0xa 0x8001
 ./tpmc definespace 0x1008 0xc 0x1
 touch tpm-owned
 
-echo "TEST: bad kernel space size" >> log
 $ctr log
 
+# Kernel space with wrong size AND bogus space to exhaust nvram
+echo "TEST: bad kernel space size and no room" >> log
+
+rm space.*
+echo 1500 > nvram.freespace
+
+./tpmc definespace 0x1007 0xa 0x8001
+./tpmc definespace 0x1008 0x1 0x1
+space_hog_size=$(printf "0x%x" \
+  $(( $(cat nvram.freespace) - $space_overhead - 1 )) )
+echo "remaining $(cat nvram.freespace) bytes" >> log
+echo "hogging $(( $space_hog_size )) bytes" >> log
+./tpmc definespace 0xcafe $space_hog_size 0x1 || echo "hogging failed!" >> log
+touch tpm-owned
+
+$ctr log
